//FOR LOCAL STORAGE KEYS
export const SOUND_KEY = "SOUND_KEY";
export const VERB_FORMS_KEY = "VERB_FORMS_KEY";
export const VERB_EXAMPLES_KEY = "VERB_EXAMPLES_KEY";
export const PREPOSITIONS_LIST_KEY = "PREPOSITIONS_LIST_KEY";
export const PREPOSITIONS_KEY = "PREPOSITIONS_KEY";
export const COMMON_CONTRACTIONS_KEY = "COMMON_CONTRACTIONS_KEY";
export const LAST_SYNCED_AT_KEY = "LAST_SYNCED_AT_KEY";

//FOR ENUMS
export enum WELCOME_SCREEN_REDIRECT_TO {
  VERB_FORMS = "VERB_FORMS",
  PREPOSITIONS = "PREPOSITIONS",
  VERB_EXAMPLES = "VERB_EXAMPLES",
  COMMON_CONTRACTIONS = "COMMON_CONTRACTIONS",
  SETTING_SCREEN = "SETTING_SCREEN",
  BASICS_OF_FRENCH = "BASICS_OF_FRENCH",
}
